### PR TITLE
Revert "Fix image_resize nodelet (#299)"

### PR DESCRIPTION
**Pull request by knorth55**
This reverts commit 32e19697ebce47101b063c6a02b95dfa2c5dbc52.

As discussion in #299, I strongly want to revert the PR first to make `image_proc/resize` work fine.

cc. @wkentaro @furushchev @bikramak @efernandez

### CODE REVIEW

**Comment by efernandez** [comment]
I'm happy with either reverting or accepting #309 (although #309 won't fix all issues as @knorth55 already mentioned in #299).

:+1:

**Comment by tfoote** [comment]
Is there a resolution for this? We're [holding the Kinetic sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2017-11-29/3275/4?u=tfoote) pending this arriving.

**Comment by knorth55** [comment]
no, we have got no comment about this issue from maintainers...

**Comment by tfoote** [comment]
@vrabaud I know you're busy for the next couple of days. Since this is blocking the release I'm going to go ahead and merge and push a patch release with this and the one merged change because the attempted rollback failed: https://github.com/ros/rosdistro/pull/16558 and this has had several confirmations of fixing the issue.

**Pull request merged**
