### PR TITLE
stereo_image_proc: disparity_node: Add parameter to control camera_in…

### PR DESCRIPTION
**Pull request by quic-zhaoyuan**
**Issue background:**
Unable to distinguish or remap left and right camera_info when using image_transport with identical topic names

**Description:**
When using DisparityNode from the stereo_image_proc package and running with ROS 2 bag or other scenarios involving image_transport, there is an issue if the camera_info topics for the left and right cameras are automatically derived and end up having the same name.
image
This happens because image_transport::getCameraInfoTopic derives camera_info topic names from the image topics (left/image_rect and right/image_rect). 
This makes it impossible to use the node properly in these scenarios, especially when working with recorded data or custom remapping.

**Proposed Solution**

I propose adding a parameter, use_image_transport_camera_info (default: true), to control whether DisparityNode uses image_transport::getCameraInfoTopic for deriving camera_info topics.

    Default Behavior (backward compatible):
        When use_image_transport_camera_info is true, the node continues using image_transport::getCameraInfoTopic for camera_info resolution, maintaining existing functionality.

    Custom Behavior:
        When use_image_transport_camera_info is false, the node directly uses the camera_info topics specified via remapping (e.g., left/camera_info and right/camera_info), bypassing image_transport's derivation logic.

This solution allows users to explicitly remap the camera_info topics for both cameras, providing flexibility for scenarios where topic names are not unique or need customization.

### CODE REVIEW

**Comment by quic-zhaoyuan** [comment]
**Issue background:**
Unable to distinguish or remap left and right camera_info when using image_transport with identical topic names


**Description:**
When using DisparityNode from the stereo_image_proc package and running with ROS 2 bag or other scenarios involving image_transport, there is an issue if the camera_info topics for the left and right cameras are automatically derived and end up having the same name.
image
This happens because image_transport::getCameraInfoTopic derives camera_info topic names from the image topics (left/image_rect and right/image_rect). 
This makes it impossible to use the node properly in these scenarios, especially when working with recorded data or custom remapping.

**Proposed Solution**

I propose adding a parameter, use_image_transport_camera_info (default: true), to control whether DisparityNode uses image_transport::getCameraInfoTopic for deriving camera_info topics.

    Default Behavior (backward compatible):
        When use_image_transport_camera_info is true, the node continues using image_transport::getCameraInfoTopic for camera_info resolution, maintaining existing functionality.

    Custom Behavior:
        When use_image_transport_camera_info is false, the node directly uses the camera_info topics specified via remapping (e.g., left/camera_info and right/camera_info), bypassing image_transport's derivation logic.

This solution allows users to explicitly remap the camera_info topics for both cameras, providing flexibility for scenarios where topic names are not unique or need customization.

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to target `rolling` ? then we can backport this to other distros. 

Can you add some documentation? You can add a README.md in the `stereo_image_proc` package

**Comment by quic-zhaoyuan** [comment]
Hi @ahcorde 
No problem I will prepare another change to rolling and also document

**Comment by mikeferguson** [comment]
Please don't add a REAMDE - documentation should go into the doc/components.rst file so that it gets automatically built into http://docs.ros.org/en/rolling/p/stereo_image_proc/doc/components.html

You can add it as another parameter (just follow the existing formatting)

**Comment by quic-zhaoyuan** [comment]
Hi @mikeferguson 
Understood, will do, I am working on the function verification on Rolling, will update today


Thanks,
Zhaoyuan

**Pull request closed without merging**
