### PR TITLE
load image_rotate::ImageRotateNode as component

### PR DESCRIPTION
**Pull request by mikeferguson**
This is a fixed version of #820 - targeting iron

### CODE REVIEW

**Comment by mikeferguson** [comment]
There is something wrong with our config for Iron targeted PRs - looking into what that is

**Comment by mikeferguson** [comment]
@tfoote have you ever seen this? The build log shows:

```
 > git rev-parse origin/iron^{commit} # timeout=10
18:47:26 FATAL: Command "git rev-parse origin/iron^{commit}" returned status code 128:
18:47:26 stdout: origin/iron^{commit}
18:47:26 
18:47:26 stderr: fatal: ambiguous argument 'origin/iron^{commit}': unknown revision or path not in the working tree.
18:47:26 Use '--' to separate paths from revisions, like this:
18:47:26 'git <command> [<revision>...] -- [<file>...]'
18:47:26 
```

But the "iron" branch clearly exists. I can't seem to find anything that would cause this - but it's the same on every PR we have open against the iron branch. Note: the iron branch is ~3 days old, we updated rosdistro 2 days ago to reflect the forking from rolling.

**Comment by tfoote** [comment]
I haven't seen this before. I think that the "ambiguous" is more I think about a ref collision than a missing one. I tried clearing the workspace if there was a collision with past merges/ceckouts. There was a weird cascade of rebuilds. But maybe there was a branch in the past with the same name. 

I'll try to retrigger again

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by tfoote** [comment]
That looks to have made it happy again. @mikeferguson 

PS to retrigger see my phrase above it has to be exact

**Comment by mikeferguson** [comment]
@tfoote thanks!

**Pull request merged**
