### PR TITLE
distortion_coefficients size (cols) is not fixed, it depends on distortion mododel

### PR DESCRIPTION
**Pull request by k-okada**
discussed in #278, as discussed CameraInfo.msg, 
```
float64[] D
```
the size of D should not be fixed number (5)

c.f. http://docs.ros.org/api/sensor_msgs/html/msg/CameraInfo.html

NOTE : I haven't tested this code yet, someone?

### CODE REVIEW

**Comment by k-okada** [comment]
Travis errored due to
```
0 upgraded, 0 newly installed, 0 to remove and 178 not upgraded.
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-indigo-eigen-conversions] failed
  apt: Failed to detect successful installation of [ros-indigo-eigen-conversions]
The command "rosdep install -q -y -r --from-paths src --ignore-src --rosdistro $ROS_DISTRO" failed and exited with 1 during .

```
so can someone restart travis?
Cc: @vrabaud

**Comment by JWhitleyWork** [comment]
@k-okada - I know this is very old, but would you mind rebasing this on `melodic` to pull in new CI?

**Comment by k-okada** [comment]
@JWhitleyAStuff  please restart travis test
https://api.travis-ci.org/v3/job/381034125/log.txt
```
0 upgraded, 0 newly installed, 0 to remove and 178 not upgraded.
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-indigo-eigen-conversions] failed
  apt: Failed to detect successful installation of [ros-indigo-eigen-conversions]
The command "rosdep install -q -y -r --from-paths src --ignore-src --rosdistro $ROS_DISTRO" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by SteveMacenski** [comment]
@k-okada toggling for travis.

(@JWhitleyAStuff it appears I dont have CircleCI admin rights to retrigger a failed build, can you add me to that?)

**Comment by JWhitleyWork** [comment]
@k-okada I changed the base branch for the PR but this is not the same as rebasing your branch. Please perform the following commands on your fork:

    git remote add upstream https://github.com/ros-perception/image_pipeline
    git fetch upstream
    git checkout indigo
    git checkout -b melodic
    git merge upstream/melodic
    git push --set-upstream origin melodic
    git checkout fix_278
    git rebase melodic
    <fix conflicts>
    git push -f

The general idea is to rebase your changes on the commits made to the melodic branch. This will pull in all new fixes and the CI script for CircleCI to your PR.

*edit*: Tested the above commands and they should work for you.

**Comment by JWhitleyWork** [comment]
@SteveMacenski - Log in to CircleCI with your GitHub account and add this repo as a project. It should give you access to control the build jobs after that.

**Comment by SteveMacenski** [comment]
Got it, thanks for the help

**Comment by valgur** [comment]
This change was included in #433. Can be closed.

**Pull request closed without merging**
