### PR TITLE
Add rclcpp and rclcpp_components dependencies to package.xml. (#569)

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Forward-port of #569 to Foxy.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@nuclearsandwich Can I get a quick review?

**Comment by JWhitleyWork** [comment]
The build farm "failures" are due to warnings about deprecated CMake commands. However, I'll be updating all CMake files in this repo to use `ament_auto` which will fix any such issues so please ignore those failures for now.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by JWhitleyWork** [comment]
Thanks!

**Comment by nuclearsandwich** [comment]
> Forward-port of #569 to Foxy.

Sorry, I should have checked whether this was an issue on mainline distros. For my future edification am I correct that targeting the mainline and then backporting is preferred to targeting a stable distribution and forward-porting?

**Comment by JWhitleyWork** [comment]
@nuclearsandwich Yeah, generally. No big deal, though. I'm working on a big overhal of the CMakeLists.txt and package.xml files in this distro. When I'm done, would you mind reviewing it? Maintainership is getting a bit thin on this repo (no future responsibility implied with the review of this PR).

**Comment by nuclearsandwich** [comment]
> When I'm done, would you mind reviewing it

With the disclaimer that I'm rather overwhelmed by notifications, I will do my best to do so once tagged.

**Comment by JWhitleyWork** [comment]
Totally understand. Thanks!

**Pull request merged**
