### PR TITLE
Update fisheye distortion model definition

### PR DESCRIPTION
**Pull request by DavidTorresOcana**
Update fisheye distortion model definition.
Replaces #581 retargeting to `noetic`

Update calibration tool distortion model for fisheye camera to be compatible with ros-perception/vision_opencv#306 and ros-perception/image_common#146 in as indicated in ros/common_msgs#151.

### CODE REVIEW

**Comment by mintar** [comment]
+1

This is the correct thing to do. See [my comment on common_msgs#151](https://github.com/ros/common_msgs/pull/151#issuecomment-659981501) for the full explanation.

**Comment by JWhitleyWork** [comment]
@DavidTorresOcana @mintar Is this PR dependent upon the others? It looks like it builds without it but we're talking about a text string that probably doesn't have a definition backing it until at least ros-perception/vision_opencv#306 is merged, right?

**Comment by DavidTorresOcana** [comment]
@JWhitleyWork  This PR does not depends on ros-perception/vision_opencv#306 nor ros-perception/vision_opencv#358

It simply renames the distortion model the tool gives to the distortion model already defined in [ros/common_msgs](https://github.com/ros/common_msgs/blob/noetic-devel/sensor_msgs/include/sensor_msgs/distortion_models.h#L47) so that they match. So those two need to be the same. 

See this [PR comments](https://github.com/ros/common_msgs/pull/151#issuecomment-659981501)

**Comment by JWhitleyWork** [comment]
Thanks for the clarification. LGTM!

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
