### PR TITLE
add launch examples for image and mono and stereo

### PR DESCRIPTION
**Pull request by yechun1**
* launch default file
ros2 launch image_publisher image_publisher_file.launch.py

* launch monocular camera (/dev/video0)
ros2 launch image_publisher image_publisher_mono.launch.py

* launch stereo camera (/dev/video0 and /dev/video1)
ros2 launch image_publisher image_publisher_stereo.launch.py

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@yechun1 can you fixthis PR to contain only your launch files? There's about 5,000 lines and some commits that aren't probably intended.

I'll merge then

**Comment by yechun1** [comment]
@SteveMacenski  Sure, I'll resubmit the PR very soon.

**Comment by yechun1** [comment]
Resubmitted the PR, please help review 

[image_publisher] launch examples for file and mono and stereo

launch examples to support:
1) load local image file and publish to the ros topic
1) load mono usb camera /dev/video0 and publish to the ros topic
1) load two usb cameras /dev/video0 amd /dev/video1, and publish to the left and right ros topic, this could simulate stereo camera.

* Publish image file to topic
  $ros2 launch image_publisher image_publisher_file.launch.py
    /camera/camera_info
    /camera/image_raw

* Publish monocular camera (/dev/video0)
  $ros2 launch image_publisher image_publisher_mono.launch.py
    /camera/camera_info
    /camera/image_raw

* Publish stereo camera (/dev/video0 and /dev/video1)
  $ros2 launch image_publisher image_publisher_stereo.launch.py
    /left/camera_info
    /left/image_raw
    /right/camera_info
    /right/image_raw

**Review by SteveMacenski — APPROVED** [review]
LGTM

**Comment by SteveMacenski** [comment]
@yechun1 you're failing CI on essentially linter garbage, can you fix?

**Comment by ghost** [comment]
Hi @SteveMacenski , sorry for forgetting to run the test, now the issue fixed and CI test passed.

**Pull request merged**
