### PR TITLE
Refactor stereo_image_proc tests

### PR DESCRIPTION
**Pull request by jacobperron**
- Fixed some deprecation warnings (4543634)
- Increased test timeouts to 60 seconds (35dd2a7)
  - Locally, I've observed it can take up to 40 seconds to complete one of the tests when the host is under high stress. Hopefully, this will make the tests less flaky.
- Cleanup (c051070)

### CODE REVIEW

**Review by JWhitleyWork — APPROVED** [review]
LGTM!

**Comment by JWhitleyWork** [comment]
@jacobperron Would you mind back-porting this to Dashing? I have seen these tests fail occasionally in CI.

**Comment by jacobperron** [comment]
@JWhitleyWork I've backported the test fix in #594. I don't believe the other changes in this PR are compatible with Dashing.

**Comment by JWhitleyWork** [comment]
Thanks, @jacobperron!

**Pull request merged**
