### PR TITLE
Added sensor_msgs::Image conversion to cv::Mat from rqt_image_view in order to be able to create videos from kinect depth images (cv_bridge currently doesn't support 16UC1 image encoding).

### PR DESCRIPTION
**Pull request by carlosmccosta**
Code adapted from:
https://github.com/ros-visualization/rqt_common_plugins/blob/groovy-devel/rqt_image_view/src/rqt_image_view/image_view.cpp

### CODE REVIEW

**Comment by vrabaud** [comment]
hmmm, what do you think of actually having this functionality be part of cv_bridge ? Maybe as a function like toDisplayCvShare or something ?

**Comment by carlosmccosta** [comment]
Thanks for the feedback :)
Integration within cv_bridge would be ideal to reduce code duplication in the future.
I created a PR with the implementation of the function
CvImageConstPtr cvtColorForDisplay(const sensor_msgs::ImageConstPtr& source,
                                   const std::string& encoding,
                                   bool use_dynamic_image_value,
                                   double min_image_value,
                                   double max_image_value)

PR:
https://github.com/ros-perception/vision_opencv/pull/75

Have a nice day :)

**Comment by vrabaud** [comment]
Hey, can you please squash your commits ? Thx !

**Comment by carlosmccosta** [comment]
Squashed the 3 commits into 1 as requested.
Thanks for improving cv_bridge :)

Have a nice day :)

**Pull request merged**
