### PR TITLE
Implemented extracting raw image data

### PR DESCRIPTION
**Pull request by Fruchtzwerg94**
Implementation of the raw image extraction if the file extension is "*.raw". This file extension is not supported by cv::imwrite so there is be no conflict. The raw files only containing the pixel data without any meta data which allows usage in MATLAB or other tools.

I also added a warning if OpenCV failed to save an image file.

### CODE REVIEW

**Review by JWhitleyWork — APPROVED** [review]

**Review by SteveMacenski — COMMENTED** [review]
This seems like a pretty strange special use-case that I don't think necessarily needs to be supported in this node. 

I think a better way to handle this situation would be a conversion script from a image to a matlab readable file rather than adding this. This seems to make the code less readable and confusing what ".raw" means and why that this is needed or how it should be properly used.

**Comment by Fruchtzwerg94** [comment]
Sure @SteveMacenski , extracting raw images is a special use case but a very interesting one. I don't like the solution using additional scripts since the job can be done very easily in the extractor. Code readability is not as good as before, maybe some additional comments are the solution.

Nevertheless, the current implementation ignores the return value of `imwrite`. The check I've implemented in the commit should be added definitely:
`
if (cv::imwrite(filename, image) == false)
{
    ROS_WARN_STREAM("Failed to save image " << filename);
}
`

**Comment by SteveMacenski** [comment]
@Fruchtzwerg94 that's true, but if we make it a script then we can make it a catkin global so it can be generally used in any number of other applications. Making it a separate script to open an openCV image -> convert to matlab readable -> save back could have alot of use in other packages or projects.

**Comment by Fruchtzwerg94** [comment]
From my point of view, a direct integration in the existing code is more handy @SteveMacenski . But I will not force anybody to integrate the changes. What do you think @JWhitleyAStuff . Would it be better to create a script here? If yes, I could change  (simplify) this pull request to only handle the failure case already mentioned above.

**Comment by SteveMacenski** [comment]
A third opinion is always good :-)

**Comment by JWhitleyWork** [comment]
Honestly, I'm inclined to agree with @Fruchtzwerg94. It's a fairly small change but:

1. *.raw images are used outside of Matlab (e.g. Adobe products, other image editing software, etc.) and retain more image data than their compressed counterparts.
2. It won't affect any other types.
3. Saving directly from the node keeps from adding in a compression/decompression step which loses data.

Just my opinion.

**Comment by SteveMacenski** [comment]
Ok that's fine, we can do that then.

I was trying ot think about portability. THis might be a useful little conversion script  for other people to be able to `./convert image.jpg image.raw` as a general use and could find value in other places.

**Review by SteveMacenski — APPROVED** [review]

**Comment by Fruchtzwerg94** [comment]
Thanks for the discussion and merge @SteveMacenski and @JWhitleyAStuff . I've also created a pull request to backport the changes to kinetic. You can find the backport merge at #413 . I've done it similar to #406 . Would be great also to have the changes in kinetic, which is my mainly used distro.

**Comment by JWhitleyWork** [comment]
@SteveMacenski - I get where you're coming from but the problem is that, if you've already saved the image as a JPG, you've already lost quality (JPG uses compression and is therefore a lossy format) which means converting it back to .raw gets you compatibility but doesn't retain the quality. Having it included here means that the raw images from the camera can be saved without degradation due to compression.

**Comment by SteveMacenski** [comment]
huh, I didn't know it defaulted to jpg, we could add a flag for png which should be lossless: https://docs.opencv.org/3.0-alpha/modules/imgcodecs/doc/reading_and_writing_images.html#imwrite

**Pull request merged**
