### PR TITLE
changed file numbering from %04i to %06i due to the need of saving mo…

### PR DESCRIPTION
**Pull request by zwenga**
Changed file numbering from %04i to %06i due to the need of saving more than 10000 images. There is no possibility known to me to change the numbering from outside, so the numbering should be at least as high as %06i.

### CODE REVIEW

**Comment by wkentaro** [comment]
I have been thinking about the filename rules of image saving in this repo,
and in my opinion the node should support image saving with timestamp in filename.
What do you think about this, there is no duplication in filename in this case?

**Comment by wkentaro** [comment]
I found the solution for that in `video_recorder.cpp` : https://github.com/ros-perception/image_pipeline/pull/203
This issue seems fixed with same approach.

**Comment by JWhitleyWork** [comment]
Is this still an issue? I know it's been a long time but we're trying to clear the backlog.

**Comment by JWhitleyWork** [comment]
Closing stale issue.

**Pull request closed without merging**
