### PR TITLE
[rolling] Fix image saver bug and time-based image saving

### PR DESCRIPTION
**Pull request by jacobperron**
Forward port #697 to Rolling.

### CODE REVIEW

**Comment by jacobperron** [comment]
@JWhitleyWork Friendly ping.

**Comment by JWhitleyWork** [comment]
@jacobperron Are you familiar with the failure that the CI jobs are reporting regarding missing linker references in `image_transport`? I can repro this on my machine locally as well.

**Comment by jacobperron** [comment]
@JWhitleyWork Are you referring to the disparity node test failure?

```
    RuntimeError: make_tuple(): unable to convert arguments to Python object (compile in debug mode for details)
```

I was debugging it yesterday and reported an issue upstream: https://github.com/ros2/rclpy/issues/848

I will submit a fix to stereo_image_proc shortly.

**Comment by JWhitleyWork** [comment]
@jacobperron No, I'm referring to this:

```
Starting >>> depth_image_proc
--- stderr: image_proc
/usr/bin/ld: /opt/ros/rolling/lib/libimage_transport.so: undefined reference to `rclcpp::SerializedMessage::SerializedMessage(unsigned long, rcutils_allocator_s const&)'
/usr/bin/ld: /opt/ros/rolling/lib/libimage_transport.so: undefined reference to `rclcpp::UnsupportedEventTypeException::UnsupportedEventTypeException(int, rcutils_error_state_s const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /opt/ros/rolling/lib/libimage_transport.so: undefined reference to `rclcpp::exceptions::throw_from_rcl_error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcutils_error_state_s const*, void (*)())'
collect2: error: ld returned 1 exit status
```

**Comment by jacobperron** [comment]
No, I didn't notice the linker errors.. It's odd that it only happened on the "pull_request" workflow and not the "push" workflow (aren't those supposed to be identical?).

**Comment by jacobperron** [comment]
I'm guessing the rolling docker image is not up-to-date or something.

**Comment by jacobperron** [comment]
@JWhitleyWork Yeah, I think it's because the rolling docker image is targeting the main repository (as opposed to testing):

```
# cat /etc/apt/sources.list.d/ros2-latest.list 
deb http://packages.ros.org/ros2/ubuntu focal main
```

Compared with the Rpr job, which uses the testing repository:

```
deb http://packages.ros.org/ros2-testing/ubuntu focal main
```

IMO, given the nature of Rolling, I think it makes sense to pull packages from testing.

**Comment by jacobperron** [comment]
We should consider changing the base docker image, maybe the [`testing` image](https://hub.docker.com/layers/osrf/ros2/testing/images/sha256-96c266f6fa2263860bf84e80c756d45c972e3d3a179efc1ec8b0a5abc9be72c9?context=explore).

**Comment by JWhitleyWork** [comment]
FYI - fixed a linter bug and then changed the `rolling` base image. Rebased your branch on `rolling`.

**Comment by jacobperron** [comment]
https://github.com/ros-perception/image_pipeline/pull/710 should fix the last test failure.

**Comment by JWhitleyWork** [comment]
Would you mind rebasing again?

**Comment by jacobperron** [comment]
Rebased.

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
