### PR TITLE
image_saver: Support lazy subscribing

### PR DESCRIPTION
**Pull request by furushchev**
This pull request includes following updates:

- Support lazy subscribing input topic

  Subscribing image topic to be saved only when saving is requested.

- Add `~wait_for_save` & `~save_timeout` params

  `image_saver` has three ways for saving images (though not yet documented)

  1. Oneshot save by using `~save` service
  2. Durative save by using `~start` & `~end` service
  3. Continuous save by setting `~save_all_images` param

  On oneshot way of saving, call of service `~save` did never return until no image is published from publishers, which can lock callee forever.
  With `~wait_for_save` param, we can switch whether calling `~save` request blocks until image is saved or immediately returns from the request just like a non-blocking way.
  If we choose the `~wait_for_save` as true, then we can set `~save_timeout` param to set timeout for waiting.

### CODE REVIEW

**Comment by knorth55** [comment]
@furushchev this PR needs minor bug fix. I made PR for the bug fix.
https://github.com/furushchev/image_pipeline/pull/1

**Comment by JWhitleyWork** [comment]
@furushchev - Would you mind rebasing this on `melodic`?

@knorth55 - If we don't hear back from @furushchev within a week or two, would you mind picking up this PR with your fix and rebasing on `melodic`?

**Comment by knorth55** [comment]
@JWhitleyAStuff sure, I can.

**Comment by JWhitleyWork** [comment]
@knorth55 - Would you mind taking over this one and creating a new PR with these changes and your fixes, based on `melodic`? We really appreciate your help.

**Comment by knorth55** [comment]
We want this feature in `indigo`, too because we still use `indigo` robot.
Can i also make a backport PR?

**Comment by JWhitleyWork** [comment]
@knorth55 - I'm sorry but `indigo` (and Ubuntu 14.04) are EOL. We are no longer approving new feature additions to `indigo`, just major bug fixes. Exactly for your use case: we don't want to break long-established installs.

**Comment by knorth55** [comment]
Indigo is not yet EOL, but actually today (2019/04/30) is the last day of indigo Trusty.
OK, i will open to kinetic branch.

**Comment by SteveMacenski** [comment]
@knorth55 Indigo is EOL. http://wiki.ros.org/Distributions as far as I can tell from that document is that modern ROS distros go EOL with Canonical

**Comment by knorth55** [comment]
I open #412

**Pull request closed without merging**
