### PR TITLE
add image_flip node

### PR DESCRIPTION
**Pull request by mikeferguson**
This is a continuation of https://github.com/ros-perception/image_pipeline/pull/756:

 * [x] Squashed 16 commits in original PR for ease of rebase/review
 * [x] Moved node into image_rotate package
 * [x] Added lazy subscriber
 * [x] Removes QoS parameters - will add proper QoS overrides in a different PR (when we do the same for image_rotate)
 * [x] Adds documentation

### CODE REVIEW

**Comment by mikeferguson** [comment]
After reviewing this closer - I may also make both nodes derive from a base class to avoid so much duplicated code

**Review by ahcorde — CHANGES_REQUESTED** [review]
is this PR still relevant ? there are some conflicts

**Comment by ahcorde** [comment]
@mikeferguson ready for review ?

**Comment by mikeferguson** [comment]
> @mikeferguson ready for review ?

Yes, I was originally planning to try and merge the two nodes... but, yeah, that turns out to be messier than I thought.

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@mikeferguson do you want to backport this PR ?

**Comment by mikeferguson** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
