### PR TITLE
Backport: Implemented extracting raw image data

### PR DESCRIPTION
**Pull request by Fruchtzwerg94**
Backport of #329 to _Kinetic_.

Implementation of the raw image extraction if the file extension is "*.raw". This file extension is not supported by cv::imwrite so there is be no conflict. The raw files only containing the pixel data without any meta data which allows usage in MATLAB or other tools.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@Fruchtzwerg94 - I think your `kinetic` branch is a bit out-of-date. Please pull in upstream changes to your local `kinetic` branch and then rebase your PR on those changes.

**Comment by Fruchtzwerg94** [comment]
Thanks for the hint @JWhitleyAStuff . I've pulled and pushed the changes. Since I've never did this before on GitHub I hope it's correct now. Please let me know if there are still problems.

**Comment by JWhitleyWork** [comment]
I'm not seeing any difference here. Please run the following commands:

    git checkout kinetic
    git remote add upstream https://github.com/ros-perception/image_pipeline
    git fetch upstream
    git rebase upstream/kinetic
    git push -f
    git checkout patch-1
    git rebase kinetic
    git push -f

This will update your `kinetic` branch to match ours and also base your patch off of those changes.

**Comment by Fruchtzwerg94** [comment]
Sorry @JWhitleyAStuff  , I've updated the wrong branch. Patch 1 is now also updated. Is it correct now?

**Review by JWhitleyWork — APPROVED** [review]
LGTM!

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
