### PR TITLE
Fix OpenCV4 compatibility.

### PR DESCRIPTION
**Pull request by hgaiser**
This PR adds compatibility for OpenCV4.

### CODE REVIEW

**Comment by hgaiser** [comment]
Any update on this? @vrabaud

**Comment by SteveMacenski** [comment]
@hgaiser is openCV4 used in any ROS distribution?

**Comment by JWhitleyWork** [comment]
@SteveMacenski - It isn't supported, even in ROS2 Crystal, certainly not Melodic. Maybe in Noetic, though. I'm going to close for now but we can re-open if Noetic adds support.

**Comment by SteveMacenski** [comment]
Lets not be too hasty, the ROS distribution not supporting it isn't necessarily a reason ignore it. If it doesn't break compatibility for existing openCV1,2,3 we should consider it

**Comment by hgaiser** [comment]
I agree with @SteveMacenski . There not being a ros distribution that uses opencv4 seems like a bad reason to close this. The PR is backwards compatible, there should be no harm in prematurely adding these changes, for when ros decides to support opencv4.

**Comment by JWhitleyWork** [comment]
Sorry for the hasti-ness. @hgaiser - Would you mind rebasing from or merging the changes in the `indigo` branch so your PR goes through the new CI? Also, are you actually still using this for `indigo` or have you upgraded? I would like to keep as many changes as possible moved forward out of Indigo for stability and due to it being EOL'd.

**Comment by SteveMacenski** [comment]
Indigo is EOL, we should be targeting all changes to Melodic and cherry picking down to Kinetic for big upgrades. @hgaiser thanks for the work, I'd like to see a testing plan / things you've tried to make sure it doesn't break anyone using default openCV versions in Kinetic/Melodic (opencv 2,3)

**Comment by hgaiser** [comment]
I'll update this PR later this week. A testing plan seems a bit overkill. I've changed some ifdefs that tested for opencv3, to ifdefs that test for opencv2. Additionally the header that is included has existed since opencv2. Shouldn't the unit tests handle any testing?

**Comment by JWhitleyWork** [comment]
@hgaiser - I think this is more about getting an environment set up in CI to do this test. Normally, we use the standard `ros:melodic` Docker which is going to include only OpenCV 3.2.0. Would it be possible for you to provide us with a Docker image (preferably on Docker Hub) that uses `ros:melodic` as a base and adds OpenCV 4? I don't think it's as simple as just installing OpenCV 4 (because of Melodic package dependencies) but maybe it is.

**Comment by hgaiser** [comment]
I updated it to be based from melodic.

**Comment by hgaiser** [comment]
@JWhitleyAStuff regarding the Docker image, the amount of effort to make this is unreasonable for this PR since it also requires all ROS packages linked to OpenCV to be recompiled. It has been tested on Arch Linux, which contains OpenCV4. I would wait with setting up CI for OpenCV4 until there is a ROS distribution that uses it.

**Comment by SteveMacenski** [comment]
@hgaiser a couple of questions just for my openCV4 ignorance: 
- You'd changed the conditions to set 2's as a certain thing, and 3 otherwise. Is that to mean opencv4 has the same API for all these things?
- What does `highgui_c` contain that you needed `highgui` did not? I'm struggling to see where in this PR there's a new thing called outside rearranging conditions.

I dont think the docker file is absolutely necessary as long as its been tested on your side in opencv4, we can independently test in opencv3 and opencv2. While I dont think this is going to be an issue, releasing debians for this and having it crash would be *very very bad*

**Comment by de-vri-es** [comment]
> @hgaiser a couple of questions just for my openCV4 ignorance:
> 
> You'd changed the conditions to set 2's as a certain thing, and 3 otherwise. Is that to mean opencv4 has the same+ API for all these things?

Yes, opencv4 is still mostly backwards compatible with opencv3. In general it also makes more sense to special-case older versions rather than the newest version, since it's much more likely that later versions will be similar to the current version rather than an older version.

> What does `highgui_c` contain that you needed `highgui` did not? I'm struggling to see where in this PR there's a new thing called outside rearranging conditions.

The header contains a C interface, including some non-namespaced enums that are used here and there: https://github.com/ros-perception/image_pipeline/blob/d53b457ad4512a98c0df51bb321d8e17cb66655b/image_view/src/nodes/image_view.cpp#L169

In opencv3 and earlier, the C++ interface automatically pulls in the C interface. This is no longer the case in opencv4.

Another option could be to use the namespaced enums instead of adding the `highui_c.h` header. These are also already present in opencv2. Including the header is a smaller change though.

**Comment by SteveMacenski** [comment]
Got it. Ok, given that Melodic ships with openCV3, we should at minimum validate 
- [ ] opencv4 works for you on this
- [x] opencv3 works for all others in melodic (@JWhitleyAStuff do you run melodic to test)
- [ ] opencv2 works for all users in kinetic, though we probably wont port this to kinetic (I can take this)

**Comment by SteveMacenski** [comment]
This is a great future proofing effort. I'm a fan.

**Comment by hgaiser** [comment]
I refactored the PR to be as small as possible. I chose to use the `cv::WINDOW_` definitions, instead of the `CV_WINDOW_` definitions, since this PR is set to merge with melodic (which requires opencv3). Alternatively I can change the file to include `highgui_c.h` to use the backwards compatible definitions if desired.

**Comment by JWhitleyWork** [comment]
@hgaiser Great work on this. Totally on-board with these changes.

**Comment by JWhitleyWork** [comment]
@SteveMacenski - It built against Melodic and Kinetic correctly. No runtime testing is done in the CI builds (yet) but everything compiled just fine.

**Comment by SteveMacenski** [comment]
Oh! With that refactor, yes I approve, very simple and clearly not going to break anything for non-4 users (which isnt officially supported, so my burden of proof is incredibly low)

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
With a second maintainer's approval, go ahead and merge

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
