### PR TITLE
[camera_calbration] fix typo np -> numpy

### PR DESCRIPTION
**Pull request by knorth55**
`np` is note declared. Standardize into `np` -> `numpy`

### CODE REVIEW

**Comment by vrabaud** [comment]
I'll also write a test. This error has always been here as far as I can tell no ? Or did it just appear recently.
Thx for the fix !

**Comment by knorth55** [comment]
I roughly searched its change history, but it is not a recent change.
I found this when I tried to calibrate camera with depth image, and it does occurred for color image calibration, so most people don't care about this.

**Comment by knorth55** [comment]
@vrabaud travis fails because of short storage.

```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
```

**Comment by knorth55** [comment]
@vrabaud ping
on indigo branches,  it passes. but on hydro branches, it doesn't.
i think this error is because of opencv setting

```
libdc1394 error: Failed to initialize libdc1394
```

**Comment by vrabaud** [comment]
Travis was failing in the first place because it needed an update from cv_bridge (which just got synced but only for Indigo).
Then there was the problem that you mentioned as well as other ones on Travis.
Indigo is fine for now at least so I'll merge. Thx !

**Pull request merged**
