### PR TITLE
Fixed typo in point_cloud_xyz launch file

### PR DESCRIPTION
**Pull request by hardesh**
- Fixed error in point_cloud_xyz example launch file. Changed the topic from `image_raw` to `image_rect`

Addresses https://github.com/ros-perception/image_pipeline/issues/730

### CODE REVIEW

**Review by JWhitleyWork — APPROVED** [review]

**Comment by JWhitleyWork** [comment]
LGTM. Thanks for the fix!

**Comment by flynneva** [comment]
@JWhitleyWork @hardesh do you think we could fix it for the other launch files as well...since if this is a typo then it looks like all the launch files in `depth_image_proc` need the change....

**Comment by hardesh** [comment]
Other launch files as in on other branches?

**Comment by flynneva** [comment]
@hardesh I mean other launch files on the ROS2 branch within the depth_image_proc package:


https://github.com/ros-perception/image_pipeline/tree/ros2/depth_image_proc/launch

**Comment by hardesh** [comment]
I had checked all launch files. I think only one had this issue

**Pull request merged**
