### PR TITLE
Removed basestring (no longer exists in new python 3 version).

### LINKED ISSUE #551: Saving tar fails in python 3.8
When pressing "save" in cameracalibrator, the tool fails to save the tarballs and prints:
```
...
/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 1266, in taradd
    if isinstance(buf, basestring):
NameError: name 'basestring' is not defined
```

It looks like "basestring" [is deprecated](https://docs.python.org/3.0/whatsnew/3.0.html) in python 3.8. That document recommends replacing basestring with str, however then saving still fails with

```
Traceback (most recent call last):
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/camera_calibrator.py", line 273, in on_mouse
    self.c.do_save()
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 578, in do_save
    self.do_tarfile_save(tf) # Must be overridden in subclasses
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 1279, in do_tarfile_save
    taradd('left.yaml', self.yaml("/left", self.l))
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 1275, in taradd
    tf.addfile(tarinfo=ti, fileobj=s)
  File "/usr/lib/python3.8/tarfile.py", line 1995, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/usr/lib/python3.8/tarfile.py", line 256, in copyfileobj
    dst.write(buf)
  File "/usr/lib/python3.8/gzip.py", line 276, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
```

I currently do not know enough about tarballs to fix this myself, maybe someone can have a look?

Working on noetic branch, commit 98364014ae3d4aa6ca92a0c7f6e8541ad0354675

### PR DESCRIPTION
**Pull request by PfeifferMicha**
Fixes #551

Note: Only tested on Ubuntu 20.04, python 3.8.2.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Please submit a PR for ros2 as well to fix this

**Review by SteveMacenski — APPROVED** [review]

**Comment by PfeifferMicha** [comment]
I don't have ROS 2 here (and haven't worked with it yet) - can I just add the exact same changes? I wouldn't be able to test it - someone else should.

**Comment by JWhitleyWork** [comment]
@PfeifferMicha That should be fine. CI will go over it and we can find someone to test it.

**Comment by SteveMacenski** [comment]
No idea why foxy and rolling are being run on this PR, but we can safely ignore it. @JWhitleyWork any issues?

**Review by JWhitleyWork — APPROVED** [review]
I dig it.

**Pull request merged**
