### PR TITLE
Maint/ci circleci test

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Created a new melodic-devel branch where we can work on features and bug fixes for release into Melodic.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Addresses #396.

**Comment by JWhitleyWork** [comment]
@SteveMacenski - Do you think this should be pulled into `indigo`? The down-side is that it currently tests against ROS releases after Indigo - the upside is that it guarantees forward-compatibility as well. Or maybe I should just test the `indigo` branch against Indigo and have the new `melodic-devel` test against all non-EOL distros? Thoughts?

**Comment by SteveMacenski** [comment]
I think we should release the changes we've just merged in Indigo, but all further development in melodic. Indigo shouldnt get updates anymore, it EOLd 8 days ago. Kinetic it would be nice to get updates if its not a pain.

**Comment by SteveMacenski** [comment]
Lunar EOLs in 20 days, I'd just remove that here too. Do one last release on Indigo/Lunar or leave them as is

**Comment by JWhitleyWork** [comment]
@SteveMacenski - I agree. Let me create a Kinetic branch from the current Indigo branch, then Melodic from Kinetic. I'll make this PR for Kinetic and then pull it into Melodic. I'll also make Melodic the default branch.

**Review by SteveMacenski — APPROVED** [review]

**Pull request merged**
