### PR TITLE
ros2 camera calibration, tests are strangely failing

### PR DESCRIPTION
**Pull request by klintan**
Started port of camera calibration to ROS2, would love some initial feedback and thoughts on stuff that is still missing (mostly commented out in the code)

- cv2.imshow() should not be run in a thread as per https://stackoverflow.com/questions/11623566/python-opencv-threading and http://opencv-users.1802565.n2.nabble.com/imshow-and-waitkey-from-within-a-thread-gt-not-updating-the-display-td6918493.html. The discussion that is referenced in the display thread solution implemented for ROS1 https://github.com/ros-perception/image_pipeline/issues/85 does not work on Mojave (Apple implemented stricter control on writing to the UI from non-main-threads, can't find a reference link though). Further trying to create the cv2.namedWindow in the main thread and update the imshow in a different one didn't work either, see the first sentence.
This all meant that I put the spin in a separate thread and the imshow while loop in the main thread. This could perhaps be a custom executor or something more fancy, would love some feedback on this new approach if it needs major changes.

- Tests are failing on non-ROS2-related stuff (calibration errors) which is quite serious, but the only way I can see it being related is because its now running on python 3.7 (instead of 2.x). Will try to look into it, but any pointers here are of interest as well. I will look at the CV2 calibration implementation and see if I can see any differences since I guess its based on that code.

- The service check is not implemented yet because it uses some functions I was uncertain about, such as the rospy.remap_name() and rospy.resolve_name(). 

- Did some restructuring of the projects as to the recommendations of ros2 py-packages. But would love feedback on all of this as well.

Just wanted to start this PR as a heads up as well as to get some early feedback since I new to Ros2 (and only have limited experience in ROS1 as well)

### CODE REVIEW

**Comment by klintan** [comment]
* The service check is not implemented yet because it uses some functions I was uncertain about, such as the rospy.remap_name() and rospy.resolve_name(). 

Is done, but ugly and non-ROS2 solution. As stated earlier, if someone could take a look at that, that would be awesome. Will see why the calibration tests are failing, I could be having the incorrect test files.
Would be awesome to try to merge this into the ROS2 branch eventually so that another package in the image_pipeline is available.

**Comment by klintan** [comment]
Updated some missed things from https://github.com/ahuizxc/image_pipeline/commit/5e2b4efaaa7d77410446e069780be2b6e144ed72

**Comment by yechun1** [comment]
@klintan, may I know how do you use stereo images as input resources on ROS2? Have you enabled ucv_camera to publish stereo raw image (left and right) or is there any solution to provide images for stereo calibration tests?

**Comment by klintan** [comment]
> @klintan, may I know how do you use stereo images as input resources on ROS2? Have you enabled ucv_camera to publish stereo raw image (left and right) or is there any solution to provide images for stereo calibration tests?

Unfortunately I have not tried this yet :/ but it's on my roadmap to buy a simple stereocamera and try out the calibration and everything that comes with it as well. 

For the tests I used the old ROS1 data, at least I think its that one, its available here http://download.ros.org/data/camera_calibration/camera_calibration.tar.gz

**Comment by yechun1** [comment]
Would you please share me the steps how you run camera_calibration tests with those [left/right]*.pgm files?

**Comment by klintan** [comment]
> Would you please share me the steps how you run camera_calibration tests with those [left/right]*.pgm files?

Sorry missed this, will run it through and get back to you.

**Comment by yechun1** [comment]
I have found another solution to publish left/right camera by image_publisher, with two USB camera devices and run two image_publisher node. 
here is https://github.com/ros-perception/image_pipeline/pull/386 for reference.
```
launch stereo camera (/dev/video0 and /dev/video1)
 ros2 launch image_publisher image_publisher_stereo.launch.py
```

**Comment by clydemcqueen** [comment]
It appears that the fork is gone, is this PR dead? Is there an active ros2 port for camera_calibration? Thanks.

**Comment by JWhitleyWork** [comment]
@clydemcqueen - There is a `ros2` port that is in-progress. It's on the `ros2` branch of this repo.

**Comment by klintan** [comment]
Sorry I removed it because I wanted to do some other work. I'll create a branch on my new fork and add the changes from this. I don't think anything is done on the image calibration on the ROS2 branch just yet.

**Comment by clydemcqueen** [comment]
I am happy to help review & test.

**Pull request closed without merging**
