### PR TITLE
Add nodelet to resize image and camera_info

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by vrabaud** [comment]
nice one, thx !

**Comment by wkentaro** [comment]
@vrabaud I'm adding this doc to roswiki page of image_proc, but could't find the way. Below is the window when I clicked **Edit (Text)**. Do you know something about this?
screen shot 2017-08-08 at 0 28 18

**Comment by vrabaud** [comment]
Just add an Indigo section and edit no ? Like for fuerte, the URL is: http://wiki.ros.org/action/edit/image_proc/fuerte?action=edit&editor=text

**Comment by wkentaro** [comment]
Thanks! I was editing at http://wiki.ros.org/action/edit/image_proc?action=edit&editor=text ..

**Comment by wkentaro** [comment]
Hmm, how can I manage the order of the sections?
I wrote at http://wiki.ros.org/action/edit/image_proc/indigo?action=edit&editor=text as below:
```
<<Include(image_proc/fuerte)>>

<<Version(indigo)>>
{{{
#!clearsilver CS/NodeAPI
node.0 {
  name = image_proc/resize
  desc = Takes image and/or camera info and resize them.
  sub {
    0.name = image
    0.type = sensor_msgs/Image
    0.desc = Arbitrary image.
    1.name = camera_info
    1.type = sensor_msgs/CameraInfo
    1.desc = Camera parameters.
  }
  pub {
    0.name = ~image
    0.type = sensor_msgs/Image
    0.desc = Resized image.
    1.name = ~camera_info
    1.type = sensor_msgs/CameraInfo
    1.desc = Resized camera info.
  }
}
}}}
```
and got

screen shot 2017-08-08 at 0 58 55

so should I edit the old ones like http://wiki.ros.org/action/edit/image_proc/diamondback?action=edit&editor=text , which has `== Nodelets ==` section?
Or are there some better ways?

**Comment by wkentaro** [comment]
and actually, the section order has already been broken:

screen shot 2017-08-08 at 1 03 16

**Pull request merged**
