### PR TITLE
Melodic

### PR DESCRIPTION
**Pull request by farhad-dalirani**
Solve this problem in camera calibration node (melodic):

```
super(StereoCalibrator, self).__init__(*args, **kwargs)
TypeError: super() argument 1 must be type, not classobj

```

Solution:
https://answers.ros.org/question/401020/camera_calibration-not-working-melodic-ubuntu-1804/?answer=404117#post-id-404117

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@farhad-dalirani I think you targeted the wrong branch with your changes. This was meant for melodic, correct?

**Comment by farhad-dalirani** [comment]
> @farhad-dalirani I think you targeted the wrong branch with your changes. This was meant for melodic, correct?

Yes, It was for melodic. My mistake.

**Comment by JWhitleyWork** [comment]
Your `melodic` branch does not have the fix included. Please make the change to your `melodic` branch and push the change.

**Comment by JWhitleyWork** [comment]
Ping for @farhad-dalirani

**Comment by JWhitleyWork** [comment]
Closing due to lack of response. Please re-open or create new PR and apply to `melodic` branch when ready.

**Pull request closed without merging**
