### PR TITLE
Fixes to reflect changes in pcl-1.7

### PR DESCRIPTION
**Pull request by wjwwood**
This should be merged in for `hydro`, because these changes are only for pcl-1.7.

### CODE REVIEW

**Comment by wjwwood** [comment]
@vrabaud Bump, this is blocking `image_pipeline` on the farm.

**Comment by vrabaud** [comment]
yop, on it, thx.

**Comment by wjwwood** [comment]
@vrabaud Thanks, if you could release that asap I would appreciate it.

**Comment by wjwwood** [comment]
These changes only affect/work on hydro.

That's why this devel job failed:

http://jenkins.willowgarage.com:8080/job/devel-groovy-image_pipeline/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/43/console

**Comment by vrabaud** [comment]
yeah, reverted, that's why it's taking time. Never merge after a beer :)

**Comment by wjwwood** [comment]
I should have caught that, I noted it on another package I opened a pull request for.

**Comment by vrabaud** [comment]
how would you have caught that I had drunk a beer ?

**Pull request merged**
