### PR TITLE
Update tarfile_calibration.py

### PR DESCRIPTION
**Pull request by trigal**
this commit refs #285  and solve "does not visualize rectified images after calibration" issue

### CODE REVIEW

**Comment by vrabaud** [comment]
we don't need the while anymore right ? waitKey is a blocker . We just need k = cv2.waitKey() no ?

**Comment by trigal** [comment]
technically speaking, yes. I changed that line only to change the lowest number of lines, but they're useless. I can update the pull request if needed. 

Moreover, I just tried pressing 'q' for quit and nothing happens (but only in the monocular case) but this is a new issue ...

**Comment by vrabaud** [comment]
Yes, please change. I checked the history and it seems it comes from cv.waitKeye. Not sure on how it worked in OpenCV1 but the behavior has changed anyway so we might as well change it.
For 'q', it is supposed to quit according to the doc ? If that's the case, please fix too as it is in the same part of the code.

**Comment by k-okada** [comment]
added updated version https://github.com/ros-perception/image_pipeline/pull/340

**Comment by JWhitleyWork** [comment]
This PR is super stale and @k-okada seems to have written replacements. Closing.

**Pull request closed without merging**
