### PR TITLE
Fix image view nodelet

### PR DESCRIPTION
**Pull request by yoshito-okada**
Requested in the discussion #331

### CODE REVIEW

**Comment by k-okada** [comment]
@vrabaud I think this is ok to merge, if we could not find better solution.

**Comment by yoshito-okada** [comment]
how is this going?

**Comment by JWhitleyWork** [comment]
@yoshito-okada - Maintenance has resumed on this repo. Could you possibly merge changes from `indigo` into your branch? I would like to also wait until we have #398 complete to verify cross-version compatibility.

**Comment by yoshito-okada** [comment]
@JWhitleyAStuff - Thank you for the response!  Please check a merge commit I just made.

**Comment by SteveMacenski** [comment]
Woah, I dont see any queue management here (i.e. queue size gets _really big_ because images are getting backed up). There needs to be something here to check and retain queue size so it doesn't infinitely lag on weak computers

**Comment by JWhitleyWork** [comment]
@SteveMacenski - It isn't really a "queue" so much as it is two image storage locations which are thread-safe using mutexes. The `while(true)` loop is just to try to pull the latest image from the `queued_image_` for display. If it takes too long to display an image, the `queued_image_` will be `set()` again by the callback and the old image will be de-allocated. I don't see any "queue size" growing here.

**Comment by SteveMacenski** [comment]
Ah got it. I saw get/set/pop and assumed the  data structure was a queue. All good :+1:

**Pull request merged**
