### PR TITLE
Extract images which are synchronized with message_filters

### PR DESCRIPTION
**Pull request by wkentaro**
This is a synchronizing two images version of extract_images.cpp on image_view.

### CODE REVIEW

**Comment by vrabaud** [comment]
Please add a license, and a doc on top of the file to say what it does.
You also need a catkin_install_python to install the script.

**Comment by wkentaro** [comment]
Thanks, i will change it.

I think there is high possibility that someone will need a node which subscribes more than 2 topics.
So will change it to set subscribing topics by rosparam.

**Comment by wkentaro** [comment]
I have done the changes.

**Comment by wkentaro** [comment]
Could you please review and merge?

**Comment by vrabaud** [comment]
ok, took a while to get the bandwidth: couldn't that be an extra parameter in https://github.com/ros-perception/image_pipeline/blob/indigo/image_view/src/nodes/extract_images.cpp#L144 ? Like called "images".

**Comment by wkentaro** [comment]
That's possible but it's hard to write, because c++ does not have variable length arguments.
https://github.com/ros-perception/perception_pcl/blob/jade-devel/pcl_ros/src/pcl_ros/io/concatenate_data.cpp#L118-L181

Could I replace c++ `extract_indices` to python?

**Comment by vrabaud** [comment]
ok, I indeed do not see any better solution. Maybe ROS2 and C++11 with variadic templates will help. In which case, we can remove the Python script and merge that behavior into C++.
Thx !

**Comment by wkentaro** [comment]
> ok, I indeed do not see any better solution. Maybe ROS2 and C++11 with variadic templates will help. 

I'm happy to hear that, thanks.

**Pull request merged**
