### PR TITLE
Fix calibration yaml formatting

### PR DESCRIPTION
**Pull request by DavidTorresOcana**
This PR fixes formatting of calibration tool yaml.

camera_model -> distortion_model

This issue was introduced in #440

### CODE REVIEW

**Comment by DavidTorresOcana** [comment]
It would be nice if anybody could merge this PR onto Noetic and ROS2

**Comment by JWhitleyWork** [comment]
Yeah, looks like it was a copy/paste error. Thanks for the fix!

**Comment by parameciumvance** [comment]
Why is this fix not updated to melodic release?
I mean, when apt install ros-melodic-camera-calibration, I get version 1.15.0 rather than 1.15.1

**Comment by JWhitleyWork** [comment]
@parameciumvance Thanks for bringing this up. There is definitely some funny stuff going on with the [melodic rosdistro entry](https://github.com/ros/rosdistro/blob/d4ae2b9be465fe11e7e9958d0ee4ba73b6832e84/melodic/distribution.yaml#L4672). Looking into fixing it now.

**Comment by JWhitleyWork** [comment]
Something must have gone wrong when I tried to make the Bloom PR for the 1.15.1 release and I apparently didn't fix it. This has now been corrected in a new 1.15.2 release (see [this PR](https://github.com/ros/rosdistro/pull/33848)) which also fixes the `indigo` references. Once this PR is merged and the next Melodic package sync happens, the issue should be resolved.

**Pull request merged**
