### PR TITLE
image_view: video recorder fix for conversion of fps to ros::Duration

### PR DESCRIPTION
**Pull request by angeltop**
Fix for video recording at requested FPS.
1/fps will give 0 (integer) for fps>1
1.0/fps will give a float number that will corresponding to the requested time period of recording

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
LGTM @JWhitleyAStuff

**Review by JWhitleyWork — APPROVED** [review]

**Comment by SteveMacenski** [comment]
You merged this into Indigo, you would need to rebase this into Kinetic/Melodic. All the PRs need rebasing now

**Comment by JWhitleyWork** [comment]
Oops.

**Comment by JWhitleyWork** [comment]
Shouldn't the rest go into `kinetic` or `melodic` anyway, which would still require re-basing?

**Comment by JWhitleyWork** [comment]
Also, most won't affect this specific file/line. It should be OK. I've rebased `kinetic` on `indigo` and `melodic` on `kinetic`. I think we're OK.

**Comment by SteveMacenski** [comment]
Ah yea, all look good, just a reference for all other PRs, they have to be rebased before merging

**Pull request merged**
