### PR TITLE
[image_view] Request start/end saving request by std_srvs/Trigger

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
Could you please review and merge?

**Comment by vrabaud** [comment]
a header seems like a heavy interface ? Why not a dynamic parameter that is a ros::Time ?

**Comment by wkentaro** [comment]
so user should send request like http://wiki.ros.org/hokuyo_node/Tutorials/UsingDynparamToChangeHokuyoLaserParameters#PythonAPI ?

**Comment by wkentaro** [comment]
In that case, dynamic parameter interface is heavier I think.

**Comment by vrabaud** [comment]
ok, you are right about dynamic_reconfigure.
The simplest you should use is a trigger service: http://docs.ros.org/api/std_srvs/html/srv/Trigger.html Please also need to rebase.
Very very sorry about the slowness these days, life gets in the way ...

**Comment by wkentaro** [comment]
The reason I used header as the request is to pass the timestamp to the image_view.
With trigger service, it cannot pass the timestamp so there will be a time lag between the time user really requests and actual one.

**Comment by wkentaro** [comment]
But I can use the rostime when the Trigger service is requested as the time user desires, so I will do that.

**Comment by wkentaro** [comment]
I have done. Please review again.

**Comment by wkentaro** [comment]
Friendly, ping.

**Comment by wkentaro** [comment]
ping.

**Comment by wkentaro** [comment]
ping

**Comment by wkentaro** [comment]
ping

**Comment by vrabaud** [comment]
Very very sorry for the delay, life got inthe way ...

**Comment by wkentaro** [comment]
Never mind. Thanks!

**Pull request merged**
