### PR TITLE
initial target and source vectors based on config parameters

### PR DESCRIPTION
**Pull request by dcconner**
Issue #740

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Closed/re-opened to trigger CI jobs.

**Comment by JWhitleyWork** [comment]
Needs minor linter fix. Please see CI failures.

**Comment by mikeferguson** [comment]
Alternate implementation https://github.com/ros-perception/image_pipeline/pull/862 - that simply reorders parameter declaration and callback definition

**Comment by mikeferguson** [comment]
Alternate has been merged

**Pull request closed without merging**
