### PR TITLE
Fix wrong usage of rclcpp::Duration constructor

### PR DESCRIPTION
**Pull request by ivanpauno**
See https://github.com/ros2/rclcpp/pull/1432 for an explanation of the issue.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@ivanpauno Can you please rebase your branch for this fix on the `ros2` branch on this repo? I've fixed the CI jobs so at least the Github Actions job should provide realistic results.

**Comment by ivanpauno** [comment]
> @ivanpauno Can you please rebase your branch for this fix on the ros2 branch on this repo? I've fixed the CI jobs so at least the Github Actions job should provide realistic results.

Should be fixed now

**Comment by JWhitleyWork** [comment]
@ivanpauno It looks like you've introduced some formatting errors. Please see the results of the Github actions CI job.

**Comment by ivanpauno** [comment]
> @ivanpauno It looks like you've introduced some formatting errors. Please see the results of the Github actions CI job.

Fixed those

**Comment by ivanpauno** [comment]
The remaining failures seem unrelated to me

**Pull request merged**
