### PR TITLE
updated linear_error function to handle partial board views

### PR DESCRIPTION
**Pull request by JStech**
Modified `linear_error` to work with partial board views, which are now possible with a ChArUco target.

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@PfeifferMicha does this fix your issue?

@JStech were these changes made to ROS2 too to fix? (two too to)

**Comment by JStech** [comment]
Whoops, some of the fixes were just in my branch and hadn't been put in a PR yet. I've added them here (and #560). They are all for stereo calibration, though, so I'm unable to test it. I'm just basing it on the discussion on #550 .

None of the ChArUco stuff was ever implemented for ROS2. I believe this is everything that's relevant: #548 #549 #556 #558 #560 #561

**Comment by PfeifferMicha** [comment]
Hey, thanks for fixing this!

It almost works, I get one last error which is an easy fix:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/camera_calibrator.py", line 107, in run
    self.function(m)
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/camera_calibrator.py", line 188, in handle_monocular
    drawable = self.c.handle_msg(msg)
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 964, in handle_msg
    linear_error = self.linear_error(undistorted, ids, board)
  File "/home/user/Projects/ROS/catkin_ws_noetic/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 917, in linear_error
    if len(pts_in_row) <= 2: continue
TypeError: object of type 'filter' has no len()
```

Can be fixed by replacing line 914 with:
```
            #pts_in_row = filter(lambda x: row_min <= x < row_max, ids)
            pts_in_row = [x for x in ids if row_min <= x < row_max]
```

After that, monocular calibration works! :)

**Comment by JWhitleyWork** [comment]
@JStech See the fix from @PfeifferMicha. This is causing the CI tests to fail too.

**Comment by JStech** [comment]
Thanks for the fix, @PfeifferMicha .

**Pull request merged**
