### PR TITLE
quick fix to run cameracalibrator #713

### PR DESCRIPTION
**Pull request by jonathanTIE**
Without these name fixes, I can't use cameracalibrator. I don't think it's clean but I don't know enough about the package to make a proper one.  
Issue #713

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@jonathanTIE I get the change to fix the `fisheye_flags` variable, but why the change of the `if`/``else` structure?

**Comment by marshallpt** [comment]
> @jonathanTIE I get the change to fix the `fisheye_flags` variable, but why the change of the `if`/``else` structure?

I was wondering the same thing. When I tried to apply @jonathanTIE 's fix without changing the `if/else` structure, the program still crashed. 

```python
  File ".../dev_ws/install/camera_calibration/lib/python3.8/site-packages/camera_calibration/calibrator.py"", line 402, in get_corners
    for b in self._boards:
AttributeError: 'MonoCalibrator' object has no attribute '_boards'
```
So, that would be why. Their change ensures `self._boards` always gets set by adding an `else` at the end if the `if/elif` branch. Currently, there is no `else`, so if none of the `if`s trigger, `self._boards` never gets set.

However, their fork did not work for me on Foxy. It launches successfully, but it did not detect my chessboard when I held it in front of the camera. I am new to the package, so it's entirely possible I'm doing something wrong. Going off [this tutorial](https://navigation.ros.org/tutorials/docs/camera_calibration.html), it should start detecting it when I hold it in front of the camera, but it does not.

**Comment by clalancette** [comment]
I've retargeted this to the `rolling` branch, and I've also changed the if structure so that it throws an exception when you pass a pattern that isn't supported.  I *think* this is the behavior we want, though I don't have the infrastructure right now to test it.  @jonathanTIE @marshallpt Could you please test out the latest code here and let me know if it works for you?

**Comment by JWhitleyWork** [comment]
@jonathanTIE @marshallpt Are either of you able to test this?

**Comment by mikeferguson** [comment]
Assigning myself this one to review. Planning to do a full round of testing on calibration stuff in the next two weeks.

**Comment by marshallpt** [comment]
hey, sorry I never replied to the comments asking me to test this, unsure how I missed them. Back when I commented on this issue originally I was running Foxy and somehow missed that there is a `foxy` branch. I switched to that branch and no longer had any issues. complete blunder on my part.

**Comment by mikeferguson** [comment]
Tested locally, logic seems sound for the if/else changes

**Pull request merged**
