### PR TITLE
fix argument passing

### PR DESCRIPTION
**Pull request by iluetkeb**
Very simply fix for groovy-branch. Otherwise the cameracalibrator.py node will not work as described in the calibration tutorials!

### CODE REVIEW

**Comment by vrabaud** [comment]
thx !

**Comment by iluetkeb** [comment]
btw, I've got a few more changes coming up, there are many minor things broken. will submit once the whole thing works.

**Comment by vrabaud** [comment]
thx ! On Groovy ?

**Comment by iluetkeb** [comment]
yeah, on groovy (it's what our PR2 runs...).

I just noted that all the other changes are in the camera_pose stack, though, because they involve the camera_pose_calibration package.

**Pull request merged**
