### PR TITLE
image_view for ros2

### PR DESCRIPTION
**Pull request by ahuizxc**
usage for test:
image_view:
"ros2 run image_view image_view_exe --topic /camera/image --transport raw" or "ros2 run image_view image_view_exe --topic /camera/image"
image_saver:
"ros2 run image_view image_saver --topic /camera/image"
stereo_view:
"ros2 run image_view stereo_view --left_topic /camera/left_image --right_topic /camera/right_image --disparity /camera/disparity_image"
video_recoder:
"ros2 run image_view video_recoder --topic /camera/image --filename output.avi"
disparity_node:
ros2 launch image_view
"ros2 launch image_view disparity_node.launch.py"

### CODE REVIEW

**Comment by yechun1** [comment]
not all tests passed in my local, I'll try to do some changes based on this PR.

**Comment by yechun1** [comment]
@ahuizxc I did some changes based on your patch, would you please apply on your code and modify other files. here is the patch for reference: https://github.com/yechun1/image_pipeline/commit/335f5c77690859c3e347d5e0806c017645efe0ee

**Comment by ahuizxc** [comment]
@yechun1 @mjcarroll  I have made some changes to this package for better launch and more consist with ros.

**Comment by JWhitleyWork** [comment]
@ahuizxc - Please rebase your branch on the `ros2` branch. This will bring in fixes from `melodic` and the new CI.

**Comment by ahuizxc** [comment]
> @ahuizxc - Please rebase your branch on the `ros2` branch. This will bring in fixes from `melodic` and the new CI.

hi, is there anything i can do? thanks:)

**Comment by SteveMacenski** [comment]
@ahuizxc you need to rebase and fix these changes so you have just the image view stuff again.

**Comment by JWhitleyWork** [comment]
Replaced by #475

**Pull request closed without merging**
