### PR TITLE
Fix linker error caused by templating in the conversions.cpp file

### PR DESCRIPTION
**Pull request by flynneva**
Fixes linker error found by @simwijs on [this thread here](https://github.com/ros-perception/image_pipeline/commit/635bbb94a7ca72be11bb914a736b5052a6ec0b8d#commitcomment-62905772)

Essentially I made the mistake of including template implementations in the .cpp file when they all need to be in the header.

Signed-off-by: Evan Flynn <evan.flynn@apex.ai>

### CODE REVIEW

**Comment by flynneva** [comment]
@simwijs let me know if this fix solves your issue - I tested it locally using the cmake flags you mentioned and it seemed to work I think.

**Comment by simwijs** [comment]
You're fast lol :+1: 
I'll test it right away!

**Comment by simwijs** [comment]
Works beautifully. You have my :1st_place_medal: 
Nice to see an engineer in action :) Keep moving forward! Also glad to have contributed something, even though you made the fix. I learned from it! (I spent way too much time finding this error and trying to fix it when you fixed it in minutes haha)

**Comment by flynneva** [comment]
@simwijs you give me too much credit 😅 but glad to help out!

This is what open source is all about - finding bugs you otherwise would miss and fixing them together.

**Comment by flynneva** [comment]
@JWhitleyWork friendly ping, fixes a hidden bug in the `ros2` `depth_image_proc` package (template implementation in cpp file instead of all in the header)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI is failing, but that has nothing to do with this PR.  We'll fix that up separately.  This looks like a good fix to me, so merging it in.

**Comment by JWhitleyWork** [comment]
@flynneva Would you mind back-porting this to Foxy and Galactic? It appears to be present there too based on #696.

**Comment by flynneva** [comment]
@JWhitleyWork id be happy to! Sorry for causing such a stink with this.

**Comment by JWhitleyWork** [comment]
@flynneva Don't worry about it! As long as the outcome is improvement then the journey is always worth it!

**Pull request merged**
