### PR TITLE
Add fisheye rectification

### LINKED ISSUE #146: support fisheye calibration using opencv 3.0
OpenCV 3.0 now has support for fisheye lens calibration and related distortion/projection functions.
This could be used to extend ROS's support towards calibrating and processing images acquired with fisheye lenses.

http://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#fisheye

I guess one possibility is to add another distortion model keyword, which would indicate these additional functions need to be used. I believe only a skew coefficient is needed as a separate parameter for calibration.

### PR DESCRIPTION
**Pull request by DavidTorresOcana**
This PR introduces changes to be able to rectify fisheye cameras calibrated with ros-perception/image_pipeline#440 #580 and #592 and aim to Fix #146

This PR depends on ros-perception/vision_opencv#306 and it is related to ros-perception/image_common#146

As this PR only intends to upgrade `image_proc` package with fisheye support, it was tested only with monocular cameras.

It introduces:
 *  Rename class PinholeCameraModel to CameraModel and headers: PinholeCameraModel is misleading. Rename the class and file to a more general name.

     -  The class CameraModel does use the distortion model specified in the `camera_info`, including pinhole, equidistant and rational_polynomial and is able to run all methods in `image_proc`, regardless of the model used

### CODE REVIEW

**Review by SteveMacenski — CHANGES_REQUESTED** [review]
You should use image transport, and this should probably be inside of `image_proc` package, otherwise LGTM when CI is passing and targeted to melodic

**Comment by SteveMacenski** [comment]
@DavidTorresOcana this cant be merged until the upstream things have been merged that you pointed to. 

But given its just header changes, I have no issue merging once that time comes

**Comment by DavidTorresOcana** [comment]
> @DavidTorresOcana this cant be merged until the upstream things have been merged that you pointed to.
> 
> But given its just header changes, I have no issue merging once that time comes

It would be good if you could ask to push the upstream of PRs up

**Comment by SteveMacenski** [comment]
@DavidTorresOcana I don't have control over those repos

**Comment by DavidTorresOcana** [comment]
Successfully tested in `melodic` with ros-perception/vision_opencv#306 , #580 and #581 on a monocular camera

**Comment by DavidTorresOcana** [comment]
Closing since ros-perception/vision_opencv#358 was finally merged

**Pull request closed without merging**
