### PR TITLE
Fix time-stamps in Video Recorder

### PR DESCRIPTION
**Pull request by larsll**
Proposed fix for #673

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@larsll Is there a specific reason you went with `RCL_SYSTEM_TIME` instead of `RCL_ROS_TIME`? The latter allows for the use of simulated time with the `/clock` topic while the former does not. If you are replaying a bag and making a recording from it, I would assume that you would want to at least have the option to use the timestamps from the bag instead of only ever being able to use the system time.

**Comment by larsll** [comment]
> @larsll Is there a specific reason you went with `RCL_SYSTEM_TIME` instead of `RCL_ROS_TIME`? The latter allows for the use of simulated time with the `/clock` topic while the former does not. If you are replaying a bag and making a recording from it, I would assume that you would want to at least have the option to use the timestamps from the bag instead of only ever being able to use the system time.

Either option works for me - in the end I don't think it matters as the values are only used within video_recorder, and only used to ensure the right fps.

The perfect solution might be to detect what kind of clock you are receiving, but I am not sure how to do that 'correctly' based on image_msg->header.stamp.

**Comment by JWhitleyWork** [comment]
`RCL_ROS_TIME` will automatically use either the system clock or the rosbag `/clock` topic if it is available and `use_sim_time: true` is set on the node. Please use this instead.

**Comment by pmusau17** [comment]
Made requested change to RCL_ROS_TIME. [#675](https://github.com/ros-perception/image_pipeline/pull/675)

**Comment by JWhitleyWork** [comment]
Closing in favor of #675.

**Pull request closed without merging**
