### PR TITLE
Add approximate epsilon time policy support

### PR DESCRIPTION
**Pull request by ivanpauno**
See https://github.com/ros2/message_filters/pull/84

### CODE REVIEW

**Comment by ivanpauno** [comment]
cc @jacobperron

**Review by jacobperron — COMMENTED** [review]
Changes LGTM.

I guess we should make a new message_filters release before CI will pass.

**Comment by ivanpauno** [comment]
> Changes LGTM.
> 
> I guess we should make a new message_filters release before CI will pass.

Done in https://github.com/ros/rosdistro/pull/34809.
I will rerun the Rpr checker when the new release is available in the testing repo ...

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
The RPr job warnings look unrelated.

I'm not sure what's up with the GitHub CI. I don't see message_filters being installed. Maybe we need to add an `apt upgrade` command here: https://github.com/ros-perception/image_pipeline/blob/c6b33166ad569bcb76155824d31c59317e0f83ed/.github/workflows/basic-build-ci.yaml#L27

**Comment by jacobperron** [comment]
I pushed a small change to your branch to see if it fixes the workflow ([48c39d9](https://github.com/ros-perception/image_pipeline/pull/776/commits/48c39d99ff8d26eaa48b399e91f67ecf41d3e81d))

**Comment by jacobperron** [comment]
Deprecated headers are being fixed in https://github.com/ros-perception/image_pipeline/pull/777

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
