### PR TITLE
Add missing test dependency

### PR DESCRIPTION
**Pull request by jacobperron**
I'm hope this will fix an issue with CI.

### CODE REVIEW

**Comment by pmusau17** [comment]
Built this on ros2 foxy. All tests passed. One warning. 

```
Warning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by JWhitleyWork** [comment]
@jacobperron It looks like several of the `stereo_image_proc` tests timed out.

**Comment by pmusau17** [comment]
@jacobperron @JWhitleyWork I have a fix for the timeout [here](https://github.com/ros-perception/image_pipeline/pull/674)

**Comment by jacobperron** [comment]
Rebased.

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
