### PR TITLE
Added stereo calibration using charuco board

### PR DESCRIPTION
**Pull request by MRo47**
From #972 
Doing this first for rolling.

This was a TODO in the repository, opening this PR to add this feature.
- The main issue why this wasn't possible imo is the way `mk_obj_points` works. I'm using the inbuilt opencv function to get the points there.
- The other is a condition when aruco markers are detected they are added as good points, This is fine in case of mono but in stereo these have to be the same number as the object points to find matches although this should be possible with aruco.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
tests are failing https://build.ros2.org/job/Rpr__image_pipeline__ubuntu_noble_amd64/4/

**Comment by MRo47** [comment]
@ahcorde my bad, thought there was some rosdep issue in pipeline. Fixed now

**Comment by MRo47** [comment]
@ahcorde any reason we are waiting on this?

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy iron

**Pull request merged**
