### PR TITLE
Don't use GTK for android

### PR DESCRIPTION
**Pull request by garyservin**
Avoid using GTK when building for Android

### CODE REVIEW

**Comment by trainman419** [comment]
It's probably better to do this by checking the cmake `GTK_FOUND` variable and setting `-DHAVE_GTK` appropriately.

**Comment by vrabaud** [comment]
what's the behavior on Android for `find_package(GTK2)` ? Should that be a `find_package(GTK2 QUIET)` ?

**Comment by vrabaud** [comment]
actually, image_view is a GUI. For Android, we should simply skip the GUI executables / libs no ?

**Comment by vrabaud** [comment]
@garyservin , any comments on the above ?

**Comment by garyservin** [comment]
Sorry for the delay!

I agree with skipping GUI executables and libs.

Just to confirm. We should skip image_view, image_view_exe disparity_view, stereo_view, right?

This leaves extract_images image_saver and video_recorder to be compiled on Android. What's the best approach for  installing the targets? To separate the GUI ones from the extra tools perhaps?

**Comment by vrabaud** [comment]
can you pleae confirm master works for you ? Thx

**Comment by trainman419** [comment]
I still think that this should be done differently:

```
find_package(GTK2)
if(GTK2_Found)
   ... GUI executables here
endif()
```

This will better handle other platforms where a GUI or GTK2 may not be available.

**Comment by vrabaud** [comment]
well, the package has a dependency on GTK so it will be installed anyway during build time. Or you prevent that on Android ?

**Comment by garyservin** [comment]
I can confirm that it builds on Android!

GTK does not create any issue when building and I haven't seen anything in the logs about it

**Pull request closed without merging**
