### PR TITLE
Backport "Fix ResizeNode to allow remapping both image and camera_info topics #693"

### PR DESCRIPTION
**Pull request by schornakj**
Backport the fix for `image_proc::ResizeNode` from #693 to the `humble` branch.

### CODE REVIEW

**Comment by Wojcik98** [comment]
Hey @JWhitleyWork, could you please review this PR and merge it?

Edit: or I will make a PR fixing this issue for the rest of the nodes as well, since they will also have this bug.

**Comment by JWhitleyWork** [comment]
@Wojcik98 / @schornakj Sorry for the delay. Can you please resolve the conflicts that have appeared in this PR?

**Comment by Wojcik98** [comment]
@JWhitleyWork #818 already implemented this, I think we can close this PR.

**Comment by schornakj** [comment]
@Wojcik98 thanks, glad you got that in!

**Pull request closed without merging**
