### PR TITLE
[depth_image_proc/register] option to fill sparsity holes on upsampling

### PR DESCRIPTION
**Pull request by ipa-rmb**
Added the option to fill the sparse areas with nearest neighbor depth values on upsampling operations in depth_image_proc/register . We make use of this function quite frequently. The PR does not alter the standard behavior.

### CODE REVIEW

**Comment by ipa-rmb** [comment]
Hello, could any maintainer please comment or merge this PR? Many thanks!

**Review by SteveMacenski — APPROVED** [review]
I'm OK with this -- @JWhitleyAStuff ?

**Comment by JWhitleyWork** [comment]
I've got some formatting and C++-y complaints but nothing technical. They can be fixed when I lint the ROS1 side in the near future.

**Comment by JWhitleyWork** [comment]
@SteveMacenski - I'm guessing you didn't intend for this to target `indigo`?

**Comment by SteveMacenski** [comment]
That would be correct. I’ll add to my queue to revert and retarget to melodic

**Pull request merged**
