### PR TITLE
Patch boost failure in image_view

### PR DESCRIPTION
**Pull request by SteveMacenski**
For foxy release

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Build says it's now missing dependency reference to GTK3 as well: 

```
12:02:00 CMake Warning at CMakeLists.txt:36 (find_package):
12:02:00   By not providing "FindGTK3.cmake" in CMAKE_MODULE_PATH this project has
12:02:00   asked CMake to find a package configuration file provided by "GTK3", but
12:02:00   CMake did not find one.
12:02:00 
12:02:00   Could not find a package configuration file provided by "GTK3" with any of
12:02:00   the following names:
12:02:00 
12:02:00     GTK3Config.cmake
12:02:00     gtk3-config.cmake
12:02:00 
12:02:00   Add the installation prefix of "GTK3" to CMAKE_PREFIX_PATH or set
12:02:00   "GTK3_DIR" to a directory containing one of the above files.  If "GTK3"
12:02:00   provides a separate development package or SDK, be sure it has been
12:02:00   installed.
```

**Comment by SteveMacenski** [comment]
I see `<depend>gtk3</depend>` in the package.xml. Its also a valid rosdep key https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1314

The summary at the end only lists camera_calibration as a fail though: 

```

12:02:23 Summary: 7 packages finished [21.8s]
12:02:23   1 package failed: camera_calibration
12:02:23   1 package had stderr output: camera_calibration
12:02:23 # END SUBSECTION
```

**Comment by SteveMacenski** [comment]
@JWhitleyWork 

```

12:17:57     from camera_calibration.calibrator import MonoCalibrator, StereoCalibrator, \
12:17:57 src/camera_calibration/calibrator.py:41: in <module>
12:17:57     import cv_bridge
12:17:57 /opt/ros/foxy/lib/python3.8/site-packages/cv_bridge/__init__.py:6: in <module>
12:17:57     from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
12:17:57 E   SystemError: initialization of cv_bridge_boost raised unreported exception
12:17:57 ---- generated xml file: /tmp/ws/test_results/camera_calibration/pytest.xml ----
```

This looks alot like an issue with vision_opencv not this repo, correct?

**Comment by JWhitleyWork** [comment]
>This looks alot like an issue with vision_opencv not this repo, correct?

It does appear that way.

**Comment by SteveMacenski** [comment]
@JWhitleyWork what do you think? Should I merge and release this so I stop getting the image_view build failure messages? CI is failing due to `camera_calibration` from the cv_bridge error. I filed a ticket https://github.com/ros-perception/vision_opencv/issues/339

You should also update your maintainer email. Its still the astuff email so you're not getting the failure emails

**Comment by JWhitleyWork** [comment]
@SteveMacenski There seems to be an error with `camera_calibration` in this one too. Give me a sec to update the CI images to the official ones instead of my custom ones and then you should rebase and see if it still exists.

**Comment by SteveMacenski** [comment]
@JWhitleyWork the camera_calibration failure is the `cv_bridge` failure if you look at it.

**Comment by JWhitleyWork** [comment]
@SteveMacenski Yeah, you're right. Go ahead.

**Comment by SteveMacenski** [comment]
But I'm a little suspect right now. Ferg's PR #544 has Circle pass yet this one doesn't. Maybe just need to rebase? Not sure why his is OK but this one is not given it only impacts image_view

**Comment by JWhitleyWork** [comment]
I'm getting the error in Circle now too. Current `config.yaml` on `ros2` pulls the latest source for 2 dependent packages. Using the released version causes the error.

**Review by JWhitleyWork — APPROVED** [review]
LGTM. Required to build correctly.

**Comment by SteveMacenski** [comment]
Can you clarify that? Are you saying to merge this _right now_ or after I figure out why Circle is failing? 

I'm still getting `RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime` on the cv_bridge issue.  It **builds**, it just doesn't pass **tests**.

**Comment by JWhitleyWork** [comment]
@SteveMacenski It's up to you. Two possibilities:

1. Have CircleCI mimic the build farm and fail the same way.
2. Import the source for `camera_calibration` from the upstream repo and CircleCI will pass or expose other issues until a new version of `camera_calibration` is released (at which point, switch back to doing the same thing as the farm).

Since we basically have two sets of CI, I think it's more advantageous to use 2 since we already know how it will fail on the build farm and we want to expose more stuff.

**Comment by SteveMacenski** [comment]
@JWhitleyWork camera_calibration is from this package, not an upstream repo.

**Comment by SteveMacenski** [comment]
OK added back in upstream to get circle passing.

**Pull request merged**
