### PR TITLE
Image rotate using tf2

### PR DESCRIPTION
**Pull request by garaemon**
image_rotate subscribes /tf and building tf tree consumes CPU resources a lot.
this patch supports tf2 to decrease CPU consumption. 
- ~use_tf2 parameter to switch tf and tf2

### CODE REVIEW

**Comment by vrabaud** [comment]
what's the point of adding a flag for tf2 ? This is all hapennig behind the scene so you can switch to tf2 by default no ? (and remove tf: tf actually uses tf2 behind the scene).
I have done it in indigo with 7900a4536900386bab8ea288b729adab9c1660c1 . Should I backport it ?

**Comment by garaemon** [comment]
> I have done it in indigo with 7900a45 . Should I backport it ?

cool!

the reason why I add tf2 flag is I don't know how many ros users uses tf2_buffer_server.

**Comment by ahendrix** [comment]
@vrabaud I think this is reasonable; the use_tf2 flag uses the tf2 buffer server instead of subscribing directly to the /tf fire hose.

:+1:

**Comment by garaemon** [comment]
thanks!

is it difficult to apply this patch to groovy-devel?

**Comment by vrabaud** [comment]
@garaemon  , merged in groovy

**Pull request merged**
